version: '3.8'

services:

  api:
    env_file:
      - ./server/.env
    container_name: calendapp-api-production
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000

  ui:
    env_file:
      - ./client/.env
    container_name: calendapp-ui-production
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    expose:
      - 80
    depends_on:
      - api

networks:
  default:
    external:
      name: main
