version: '3.8'

services:

  db:
    container_name: calendapp-postgres-prod
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - data:/var/lib/postgresql/data

  api:
    env_file:
      - ./server/.env
    container_name: calendapp-api-production
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 5000:5000

  ui:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    container_name: calendapp-ui-production
    ports:
      - 80:80
    depends_on:
      - api

  
volumes:
  data: