version: '3.8'

services:

  server:
    container_name: calendapp-backend
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - SECRET_JWT_SEED=SecretPassword
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./server:/app
      - node_modules_server:/app/node_modules

  client:
    container_name: calendapp-frontend
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=localhost
      - REACT_APP_API_PORT=5000
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    volumes:
      - ./client:/app
      - node_modules_client:/app/node_modules

  
  postgres:
    container_name: calendapp-postgres
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
  node_modules_server:
  node_modules_client: